/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package se.liu.ida.sambo.jdbc;

import se.liu.ida.sambo.dao.*;
import se.liu.ida.sambo.factory.*;
import se.liu.ida.sambo.dto.*;
import se.liu.ida.sambo.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PredefinedStrategiesDaoImpl extends AbstractDAO implements PredefinedStrategiesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, matchers, submatchers, weights, subweights, threshold FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, matchers, submatchers, weights, subweights, threshold ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, matchers = ?, submatchers = ?, weights = ?, subweights = ?, threshold = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column matchers
	 */
	protected static final int COLUMN_MATCHERS = 2;

	/** 
	 * Index of column submatchers
	 */
	protected static final int COLUMN_SUBMATCHERS = 3;

	/** 
	 * Index of column weights
	 */
	protected static final int COLUMN_WEIGHTS = 4;

	/** 
	 * Index of column subweights
	 */
	protected static final int COLUMN_SUBWEIGHTS = 5;

	/** 
	 * Index of column threshold
	 */
	protected static final int COLUMN_THRESHOLD = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the predefinedstrategies table.
	 */
	public PredefinedStrategiesPk insert(PredefinedStrategies dto) throws PredefinedStrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getMatchers() );
			stmt.setString( index++, dto.getSubmatchers() );
			stmt.setString( index++, dto.getWeights() );
			stmt.setString( index++, dto.getSubweights() );
			stmt.setFloat( index++, dto.getThreshold() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PredefinedStrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the predefinedstrategies table.
	 */
	public void update(PredefinedStrategiesPk pk, PredefinedStrategies dto) throws PredefinedStrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getMatchers() );
			stmt.setString( index++, dto.getSubmatchers() );
			stmt.setString( index++, dto.getWeights() );
			stmt.setString( index++, dto.getSubweights() );
			stmt.setFloat( index++, dto.getThreshold() );
			stmt.setInt( 7, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PredefinedStrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the predefinedstrategies table.
	 */
	public void delete(PredefinedStrategiesPk pk) throws PredefinedStrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PredefinedStrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the predefinedstrategies table that matches the specified primary-key value.
	 */
	public PredefinedStrategies findByPrimaryKey(PredefinedStrategiesPk pk) throws PredefinedStrategiesDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'id = :id'.
	 */
	public PredefinedStrategies findByPrimaryKey(int id) throws PredefinedStrategiesDaoException
	{
		PredefinedStrategies ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria ''.
	 */
	public PredefinedStrategies[] findAll() throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'id = :id'.
	 */
	public PredefinedStrategies[] findWhereIdEquals(int id) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'matchers = :matchers'.
	 */
	public PredefinedStrategies[] findWhereMatchersEquals(String matchers) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE matchers = ? ORDER BY matchers", new Object[] { matchers } );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'submatchers = :submatchers'.
	 */
	public PredefinedStrategies[] findWhereSubmatchersEquals(String submatchers) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE submatchers = ? ORDER BY submatchers", new Object[] { submatchers } );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'weights = :weights'.
	 */
	public PredefinedStrategies[] findWhereWeightsEquals(String weights) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE weights = ? ORDER BY weights", new Object[] { weights } );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'subweights = :subweights'.
	 */
	public PredefinedStrategies[] findWhereSubweightsEquals(String subweights) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE subweights = ? ORDER BY subweights", new Object[] { subweights } );
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the criteria 'threshold = :threshold'.
	 */
	public PredefinedStrategies[] findWhereThresholdEquals(float threshold) throws PredefinedStrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE threshold = ? ORDER BY threshold", new Object[] {  new Float(threshold) } );
	}

	/**
	 * Method 'PredefinedStrategiesDaoImpl'
	 * 
	 */
	public PredefinedStrategiesDaoImpl()
	{
	}

	/**
	 * Method 'PredefinedStrategiesDaoImpl'
	 * 
	 * @param userConn
	 */
	public PredefinedStrategiesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "dbsambo.predefinedstrategies";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PredefinedStrategies fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PredefinedStrategies dto = new PredefinedStrategies();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PredefinedStrategies[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PredefinedStrategies dto = new PredefinedStrategies();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PredefinedStrategies ret[] = new PredefinedStrategies[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PredefinedStrategies dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setMatchers( rs.getString( COLUMN_MATCHERS ) );
		dto.setSubmatchers( rs.getString( COLUMN_SUBMATCHERS ) );
		dto.setWeights( rs.getString( COLUMN_WEIGHTS ) );
		dto.setSubweights( rs.getString( COLUMN_SUBWEIGHTS ) );
		dto.setThreshold( rs.getFloat( COLUMN_THRESHOLD ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PredefinedStrategies dto)
	{
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the specified arbitrary SQL statement
	 */
	public PredefinedStrategies[] findByDynamicSelect(String sql, Object[] sqlParams) throws PredefinedStrategiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PredefinedStrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the predefinedstrategies table that match the specified arbitrary SQL statement
	 */
	public PredefinedStrategies[] findByDynamicWhere(String sql, Object[] sqlParams) throws PredefinedStrategiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PredefinedStrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
