/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package se.liu.ida.sambo.jdbc;

import se.liu.ida.sambo.dao.*;
import se.liu.ida.sambo.factory.*;
import se.liu.ida.sambo.dto.*;
import se.liu.ida.sambo.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class StrategiesDaoImpl extends AbstractDAO implements StrategiesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT Id, TermPair1, TermPair2, Matchers FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( Id, TermPair1, TermPair2, Matchers ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET Id = ?, TermPair1 = ?, TermPair2 = ?, Matchers = ? WHERE Id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE Id = ?";

	/** 
	 * Index of column Id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column TermPair1
	 */
	protected static final int COLUMN_TERM_PAIR1 = 2;

	/** 
	 * Index of column TermPair2
	 */
	protected static final int COLUMN_TERM_PAIR2 = 3;

	/** 
	 * Index of column Matchers
	 */
	protected static final int COLUMN_MATCHERS = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column Id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the strategies table.
	 */
	public StrategiesPk insert(Strategies dto) throws StrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getTermPair1() );
			stmt.setString( index++, dto.getTermPair2() );
			stmt.setString( index++, dto.getMatchers() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the strategies table.
	 */
	public void update(StrategiesPk pk, Strategies dto) throws StrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getTermPair1() );
			stmt.setString( index++, dto.getTermPair2() );
			stmt.setString( index++, dto.getMatchers() );
			stmt.setInt( 5, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the strategies table.
	 */
	public void delete(StrategiesPk pk) throws StrategiesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the strategies table that matches the specified primary-key value.
	 */
	public Strategies findByPrimaryKey(StrategiesPk pk) throws StrategiesDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria 'Id = :id'.
	 */
	public Strategies findByPrimaryKey(int id) throws StrategiesDaoException
	{
		Strategies ret[] = findByDynamicSelect( SQL_SELECT + " WHERE Id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria ''.
	 */
	public Strategies[] findAll() throws StrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY Id", null );
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria 'Id = :id'.
	 */
	public Strategies[] findWhereIdEquals(int id) throws StrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Id = ? ORDER BY Id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria 'TermPair1 = :termPair1'.
	 */
	public Strategies[] findWhereTermPair1Equals(String termPair1) throws StrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TermPair1 = ? ORDER BY TermPair1", new Object[] { termPair1 } );
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria 'TermPair2 = :termPair2'.
	 */
	public Strategies[] findWhereTermPair2Equals(String termPair2) throws StrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TermPair2 = ? ORDER BY TermPair2", new Object[] { termPair2 } );
	}

	/** 
	 * Returns all rows from the strategies table that match the criteria 'Matchers = :matchers'.
	 */
	public Strategies[] findWhereMatchersEquals(String matchers) throws StrategiesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Matchers = ? ORDER BY Matchers", new Object[] { matchers } );
	}

	/**
	 * Method 'StrategiesDaoImpl'
	 * 
	 */
	public StrategiesDaoImpl()
	{
	}

	/**
	 * Method 'StrategiesDaoImpl'
	 * 
	 * @param userConn
	 */
	public StrategiesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "dbsambo.strategies";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Strategies fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Strategies dto = new Strategies();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Strategies[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Strategies dto = new Strategies();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Strategies ret[] = new Strategies[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Strategies dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setTermPair1( rs.getString( COLUMN_TERM_PAIR1 ) );
		dto.setTermPair2( rs.getString( COLUMN_TERM_PAIR2 ) );
		dto.setMatchers( rs.getString( COLUMN_MATCHERS ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Strategies dto)
	{
	}

	/** 
	 * Returns all rows from the strategies table that match the specified arbitrary SQL statement
	 */
	public Strategies[] findByDynamicSelect(String sql, Object[] sqlParams) throws StrategiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the strategies table that match the specified arbitrary SQL statement
	 */
	public Strategies[] findByDynamicWhere(String sql, Object[] sqlParams) throws StrategiesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrategiesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
