/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package se.liu.ida.sambo.dto;

import se.liu.ida.sambo.dao.*;
import se.liu.ida.sambo.factory.*;
import se.liu.ida.sambo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class SavedPredefinedStrategiesSuggestions implements Serializable
{
	/** 
	 * This attribute maps to the column id in the savedpredefinedstrategiessuggestions table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column savedpredefinedstrategiesid in the savedpredefinedstrategiessuggestions table.
	 */
	protected int savedpredefinedstrategiesid;

	/** 
	 * This attribute maps to the column suggestionsXML in the savedpredefinedstrategiessuggestions table.
	 */
	protected String suggestionsXML;

	/** 
	 * This attribute maps to the column suggestionsVector in the savedpredefinedstrategiessuggestions table.
	 */
	protected String suggestionsVector;

	/**
	 * Method 'SavedPredefinedStrategiesSuggestions'
	 * 
	 */
	public SavedPredefinedStrategiesSuggestions()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getSavedpredefinedstrategiesid'
	 * 
	 * @return int
	 */
	public int getSavedpredefinedstrategiesid()
	{
		return savedpredefinedstrategiesid;
	}

	/**
	 * Method 'setSavedpredefinedstrategiesid'
	 * 
	 * @param savedpredefinedstrategiesid
	 */
	public void setSavedpredefinedstrategiesid(int savedpredefinedstrategiesid)
	{
		this.savedpredefinedstrategiesid = savedpredefinedstrategiesid;
	}

	/**
	 * Method 'getSuggestionsXML'
	 * 
	 * @return String
	 */
	public String getSuggestionsXML()
	{
		return suggestionsXML;
	}

	/**
	 * Method 'setSuggestionsXML'
	 * 
	 * @param suggestionsXML
	 */
	public void setSuggestionsXML(String suggestionsXML)
	{
		this.suggestionsXML = suggestionsXML;
	}

	/**
	 * Method 'getSuggestionsVector'
	 * 
	 * @return String
	 */
	public String getSuggestionsVector()
	{
		return suggestionsVector;
	}

	/**
	 * Method 'setSuggestionsVector'
	 * 
	 * @param suggestionsVector
	 */
	public void setSuggestionsVector(String suggestionsVector)
	{
		this.suggestionsVector = suggestionsVector;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SavedPredefinedStrategiesSuggestions)) {
			return false;
		}
		
		final SavedPredefinedStrategiesSuggestions _cast = (SavedPredefinedStrategiesSuggestions) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (savedpredefinedstrategiesid != _cast.savedpredefinedstrategiesid) {
			return false;
		}
		
		if (suggestionsXML == null ? _cast.suggestionsXML != suggestionsXML : !suggestionsXML.equals( _cast.suggestionsXML )) {
			return false;
		}
		
		if (suggestionsVector == null ? _cast.suggestionsVector != suggestionsVector : !suggestionsVector.equals( _cast.suggestionsVector )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + savedpredefinedstrategiesid;
		if (suggestionsXML != null) {
			_hashCode = 29 * _hashCode + suggestionsXML.hashCode();
		}
		
		if (suggestionsVector != null) {
			_hashCode = 29 * _hashCode + suggestionsVector.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SavedPredefinedStrategiesSuggestionsPk
	 */
	public SavedPredefinedStrategiesSuggestionsPk createPk()
	{
		return new SavedPredefinedStrategiesSuggestionsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "se.liu.ida.sambo.dto.SavedPredefinedStrategiesSuggestions: " );
		ret.append( "id=" + id );
		ret.append( ", savedpredefinedstrategiesid=" + savedpredefinedstrategiesid );
		ret.append( ", suggestionsXML=" + suggestionsXML );
		ret.append( ", suggestionsVector=" + suggestionsVector );
		return ret.toString();
	}

}
