/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package se.liu.ida.sambo.dto;

import se.liu.ida.sambo.dao.*;
import se.liu.ida.sambo.factory.*;
import se.liu.ida.sambo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Strategies implements Serializable
{
	/** 
	 * This attribute maps to the column Id in the strategies table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column TermPair1 in the strategies table.
	 */
	protected String termPair1;

	/** 
	 * This attribute maps to the column TermPair2 in the strategies table.
	 */
	protected String termPair2;

	/** 
	 * This attribute maps to the column Matchers in the strategies table.
	 */
	protected String matchers;

	/**
	 * Method 'Strategies'
	 * 
	 */
	public Strategies()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getTermPair1'
	 * 
	 * @return String
	 */
	public String getTermPair1()
	{
		return termPair1;
	}

	/**
	 * Method 'setTermPair1'
	 * 
	 * @param termPair1
	 */
	public void setTermPair1(String termPair1)
	{
		this.termPair1 = termPair1;
	}

	/**
	 * Method 'getTermPair2'
	 * 
	 * @return String
	 */
	public String getTermPair2()
	{
		return termPair2;
	}

	/**
	 * Method 'setTermPair2'
	 * 
	 * @param termPair2
	 */
	public void setTermPair2(String termPair2)
	{
		this.termPair2 = termPair2;
	}

	/**
	 * Method 'getMatchers'
	 * 
	 * @return String
	 */
	public String getMatchers()
	{
		return matchers;
	}

	/**
	 * Method 'setMatchers'
	 * 
	 * @param matchers
	 */
	public void setMatchers(String matchers)
	{
		this.matchers = matchers;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Strategies)) {
			return false;
		}
		
		final Strategies _cast = (Strategies) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (termPair1 == null ? _cast.termPair1 != termPair1 : !termPair1.equals( _cast.termPair1 )) {
			return false;
		}
		
		if (termPair2 == null ? _cast.termPair2 != termPair2 : !termPair2.equals( _cast.termPair2 )) {
			return false;
		}
		
		if (matchers == null ? _cast.matchers != matchers : !matchers.equals( _cast.matchers )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (termPair1 != null) {
			_hashCode = 29 * _hashCode + termPair1.hashCode();
		}
		
		if (termPair2 != null) {
			_hashCode = 29 * _hashCode + termPair2.hashCode();
		}
		
		if (matchers != null) {
			_hashCode = 29 * _hashCode + matchers.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StrategiesPk
	 */
	public StrategiesPk createPk()
	{
		return new StrategiesPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "se.liu.ida.sambo.dto.Strategies: " );
		ret.append( "id=" + id );
		ret.append( ", termPair1=" + termPair1 );
		ret.append( ", termPair2=" + termPair2 );
		ret.append( ", matchers=" + matchers );
		return ret.toString();
	}

}
