/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package se.liu.ida.sambo.dto;

import se.liu.ida.sambo.dao.*;
import se.liu.ida.sambo.factory.*;
import se.liu.ida.sambo.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class UserSessions implements Serializable
{
	/** 
	 * This attribute maps to the column id in the usersessions table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column userid in the usersessions table.
	 */
	protected int userid;

	/** 
	 * This attribute maps to the column email in the usersessions table.
	 */
	protected String email;

	/** 
	 * This attribute maps to the column ontology1 in the usersessions table.
	 */
	protected String ontology1;

	/** 
	 * This attribute maps to the column ontology2 in the usersessions table.
	 */
	protected String ontology2;

	/** 
	 * This attribute maps to the column color1 in the usersessions table.
	 */
	protected String color1;

	/** 
	 * This attribute maps to the column color2 in the usersessions table.
	 */
	protected String color2;

	/** 
	 * This attribute maps to the column matchername0 in the usersessions table.
	 */
	protected String matchername0;

	/** 
	 * This attribute maps to the column matchervalue0 in the usersessions table.
	 */
	protected String matchervalue0;

	/** 
	 * This attribute maps to the column weightvalue0 in the usersessions table.
	 */
	protected double weightvalue0;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue0 is null.
	 */
	protected boolean weightvalue0Null = true;

	/** 
	 * This attribute maps to the column matchername1 in the usersessions table.
	 */
	protected String matchername1;

	/** 
	 * This attribute maps to the column matchervalue1 in the usersessions table.
	 */
	protected String matchervalue1;

	/** 
	 * This attribute maps to the column weightvalue1 in the usersessions table.
	 */
	protected double weightvalue1;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue1 is null.
	 */
	protected boolean weightvalue1Null = true;

	/** 
	 * This attribute maps to the column matchername2 in the usersessions table.
	 */
	protected String matchername2;

	/** 
	 * This attribute maps to the column matchervalue2 in the usersessions table.
	 */
	protected String matchervalue2;

	/** 
	 * This attribute maps to the column weightvalue2 in the usersessions table.
	 */
	protected double weightvalue2;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue2 is null.
	 */
	protected boolean weightvalue2Null = true;

	/** 
	 * This attribute maps to the column matchername3 in the usersessions table.
	 */
	protected String matchername3;

	/** 
	 * This attribute maps to the column matchervalue3 in the usersessions table.
	 */
	protected String matchervalue3;

	/** 
	 * This attribute maps to the column weightvalue3 in the usersessions table.
	 */
	protected double weightvalue3;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue3 is null.
	 */
	protected boolean weightvalue3Null = true;

	/** 
	 * This attribute maps to the column matchername4 in the usersessions table.
	 */
	protected String matchername4;

	/** 
	 * This attribute maps to the column matchervalue4 in the usersessions table.
	 */
	protected String matchervalue4;

	/** 
	 * This attribute maps to the column weightvalue4 in the usersessions table.
	 */
	protected double weightvalue4;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue4 is null.
	 */
	protected boolean weightvalue4Null = true;

	/** 
	 * This attribute maps to the column matchername5 in the usersessions table.
	 */
	protected String matchername5;

	/** 
	 * This attribute maps to the column matchervalue5 in the usersessions table.
	 */
	protected String matchervalue5;

	/** 
	 * This attribute maps to the column weightvalue5 in the usersessions table.
	 */
	protected double weightvalue5;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue5 is null.
	 */
	protected boolean weightvalue5Null = true;

	/** 
	 * This attribute maps to the column matchername6 in the usersessions table.
	 */
	protected String matchername6;

	/** 
	 * This attribute maps to the column matchervalue6 in the usersessions table.
	 */
	protected String matchervalue6;

	/** 
	 * This attribute maps to the column weightvalue6 in the usersessions table.
	 */
	protected double weightvalue6;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue6 is null.
	 */
	protected boolean weightvalue6Null = true;

	/** 
	 * This attribute maps to the column matchername7 in the usersessions table.
	 */
	protected String matchername7;

	/** 
	 * This attribute maps to the column matchervalue7 in the usersessions table.
	 */
	protected String matchervalue7;

	/** 
	 * This attribute maps to the column weightvalue7 in the usersessions table.
	 */
	protected double weightvalue7;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue7 is null.
	 */
	protected boolean weightvalue7Null = true;

	/** 
	 * This attribute maps to the column matchername8 in the usersessions table.
	 */
	protected String matchername8;

	/** 
	 * This attribute maps to the column matchervalue8 in the usersessions table.
	 */
	protected String matchervalue8;

	/** 
	 * This attribute maps to the column weightvalue8 in the usersessions table.
	 */
	protected double weightvalue8;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue8 is null.
	 */
	protected boolean weightvalue8Null = true;

	/** 
	 * This attribute maps to the column matchername9 in the usersessions table.
	 */
	protected String matchername9;

	/** 
	 * This attribute maps to the column matchervalue9 in the usersessions table.
	 */
	protected String matchervalue9;

	/** 
	 * This attribute maps to the column weightvalue9 in the usersessions table.
	 */
	protected double weightvalue9;

	/** 
	 * This attribute represents whether the primitive attribute weightvalue9 is null.
	 */
	protected boolean weightvalue9Null = true;

	/** 
	 * This attribute maps to the column thresholdvalue in the usersessions table.
	 */
	protected double thresholdvalue;

	/** 
	 * This attribute maps to the column session_type in the usersessions table.
	 */
	protected String sessionType;

	/** 
	 * This attribute maps to the column sid in the usersessions table.
	 */
	protected String sid;

	/** 
	 * This attribute maps to the column step in the usersessions table.
	 */
	protected short step;

	/** 
	 * This attribute maps to the column is_finalized in the usersessions table.
	 */
	protected int isFinalized;

	/** 
	 * This attribute maps to the column user_xml in the usersessions table.
	 */
	protected String userXml;

	/** 
	 * This attribute maps to the column user_historylist_xml in the usersessions table.
	 */
	protected String userHistorylistXml;

	/** 
	 * This attribute maps to the column user_relations_historylist_xml in the usersessions table.
	 */
	protected String userRelationsHistorylistXml;

	/** 
	 * This attribute maps to the column user_suggestions_list_xml in the usersessions table.
	 */
	protected String userSuggestionsListXml;

	/** 
	 * This attribute maps to the column user_temp_xml in the usersessions table.
	 */
	protected String userTempXml;

	/** 
	 * This attribute maps to the column creation_time in the usersessions table.
	 */
	protected Date creationTime;

	/** 
	 * This attribute maps to the column last_accessed_time in the usersessions table.
	 */
	protected Date lastAccessedTime;

	/**
	 * Method 'UserSessions'
	 * 
	 */
	public UserSessions()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getUserid'
	 * 
	 * @return int
	 */
	public int getUserid()
	{
		return userid;
	}

	/**
	 * Method 'setUserid'
	 * 
	 * @param userid
	 */
	public void setUserid(int userid)
	{
		this.userid = userid;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'getOntology1'
	 * 
	 * @return String
	 */
	public String getOntology1()
	{
		return ontology1;
	}

	/**
	 * Method 'setOntology1'
	 * 
	 * @param ontology1
	 */
	public void setOntology1(String ontology1)
	{
		this.ontology1 = ontology1;
	}

	/**
	 * Method 'getOntology2'
	 * 
	 * @return String
	 */
	public String getOntology2()
	{
		return ontology2;
	}

	/**
	 * Method 'setOntology2'
	 * 
	 * @param ontology2
	 */
	public void setOntology2(String ontology2)
	{
		this.ontology2 = ontology2;
	}

	/**
	 * Method 'getColor1'
	 * 
	 * @return String
	 */
	public String getColor1()
	{
		return color1;
	}

	/**
	 * Method 'setColor1'
	 * 
	 * @param color1
	 */
	public void setColor1(String color1)
	{
		this.color1 = color1;
	}

	/**
	 * Method 'getColor2'
	 * 
	 * @return String
	 */
	public String getColor2()
	{
		return color2;
	}

	/**
	 * Method 'setColor2'
	 * 
	 * @param color2
	 */
	public void setColor2(String color2)
	{
		this.color2 = color2;
	}

	/**
	 * Method 'getMatchername0'
	 * 
	 * @return String
	 */
	public String getMatchername0()
	{
		return matchername0;
	}

	/**
	 * Method 'setMatchername0'
	 * 
	 * @param matchername0
	 */
	public void setMatchername0(String matchername0)
	{
		this.matchername0 = matchername0;
	}

	/**
	 * Method 'getMatchervalue0'
	 * 
	 * @return String
	 */
	public String getMatchervalue0()
	{
		return matchervalue0;
	}

	/**
	 * Method 'setMatchervalue0'
	 * 
	 * @param matchervalue0
	 */
	public void setMatchervalue0(String matchervalue0)
	{
		this.matchervalue0 = matchervalue0;
	}

	/**
	 * Method 'getWeightvalue0'
	 * 
	 * @return double
	 */
	public double getWeightvalue0()
	{
		return weightvalue0;
	}

	/**
	 * Method 'setWeightvalue0'
	 * 
	 * @param weightvalue0
	 */
	public void setWeightvalue0(double weightvalue0)
	{
		this.weightvalue0 = weightvalue0;
		this.weightvalue0Null = false;
	}

	/**
	 * Method 'setWeightvalue0Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue0Null(boolean value)
	{
		this.weightvalue0Null = value;
	}

	/**
	 * Method 'isWeightvalue0Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue0Null()
	{
		return weightvalue0Null;
	}

	/**
	 * Method 'getMatchername1'
	 * 
	 * @return String
	 */
	public String getMatchername1()
	{
		return matchername1;
	}

	/**
	 * Method 'setMatchername1'
	 * 
	 * @param matchername1
	 */
	public void setMatchername1(String matchername1)
	{
		this.matchername1 = matchername1;
	}

	/**
	 * Method 'getMatchervalue1'
	 * 
	 * @return String
	 */
	public String getMatchervalue1()
	{
		return matchervalue1;
	}

	/**
	 * Method 'setMatchervalue1'
	 * 
	 * @param matchervalue1
	 */
	public void setMatchervalue1(String matchervalue1)
	{
		this.matchervalue1 = matchervalue1;
	}

	/**
	 * Method 'getWeightvalue1'
	 * 
	 * @return double
	 */
	public double getWeightvalue1()
	{
		return weightvalue1;
	}

	/**
	 * Method 'setWeightvalue1'
	 * 
	 * @param weightvalue1
	 */
	public void setWeightvalue1(double weightvalue1)
	{
		this.weightvalue1 = weightvalue1;
		this.weightvalue1Null = false;
	}

	/**
	 * Method 'setWeightvalue1Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue1Null(boolean value)
	{
		this.weightvalue1Null = value;
	}

	/**
	 * Method 'isWeightvalue1Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue1Null()
	{
		return weightvalue1Null;
	}

	/**
	 * Method 'getMatchername2'
	 * 
	 * @return String
	 */
	public String getMatchername2()
	{
		return matchername2;
	}

	/**
	 * Method 'setMatchername2'
	 * 
	 * @param matchername2
	 */
	public void setMatchername2(String matchername2)
	{
		this.matchername2 = matchername2;
	}

	/**
	 * Method 'getMatchervalue2'
	 * 
	 * @return String
	 */
	public String getMatchervalue2()
	{
		return matchervalue2;
	}

	/**
	 * Method 'setMatchervalue2'
	 * 
	 * @param matchervalue2
	 */
	public void setMatchervalue2(String matchervalue2)
	{
		this.matchervalue2 = matchervalue2;
	}

	/**
	 * Method 'getWeightvalue2'
	 * 
	 * @return double
	 */
	public double getWeightvalue2()
	{
		return weightvalue2;
	}

	/**
	 * Method 'setWeightvalue2'
	 * 
	 * @param weightvalue2
	 */
	public void setWeightvalue2(double weightvalue2)
	{
		this.weightvalue2 = weightvalue2;
		this.weightvalue2Null = false;
	}

	/**
	 * Method 'setWeightvalue2Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue2Null(boolean value)
	{
		this.weightvalue2Null = value;
	}

	/**
	 * Method 'isWeightvalue2Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue2Null()
	{
		return weightvalue2Null;
	}

	/**
	 * Method 'getMatchername3'
	 * 
	 * @return String
	 */
	public String getMatchername3()
	{
		return matchername3;
	}

	/**
	 * Method 'setMatchername3'
	 * 
	 * @param matchername3
	 */
	public void setMatchername3(String matchername3)
	{
		this.matchername3 = matchername3;
	}

	/**
	 * Method 'getMatchervalue3'
	 * 
	 * @return String
	 */
	public String getMatchervalue3()
	{
		return matchervalue3;
	}

	/**
	 * Method 'setMatchervalue3'
	 * 
	 * @param matchervalue3
	 */
	public void setMatchervalue3(String matchervalue3)
	{
		this.matchervalue3 = matchervalue3;
	}

	/**
	 * Method 'getWeightvalue3'
	 * 
	 * @return double
	 */
	public double getWeightvalue3()
	{
		return weightvalue3;
	}

	/**
	 * Method 'setWeightvalue3'
	 * 
	 * @param weightvalue3
	 */
	public void setWeightvalue3(double weightvalue3)
	{
		this.weightvalue3 = weightvalue3;
		this.weightvalue3Null = false;
	}

	/**
	 * Method 'setWeightvalue3Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue3Null(boolean value)
	{
		this.weightvalue3Null = value;
	}

	/**
	 * Method 'isWeightvalue3Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue3Null()
	{
		return weightvalue3Null;
	}

	/**
	 * Method 'getMatchername4'
	 * 
	 * @return String
	 */
	public String getMatchername4()
	{
		return matchername4;
	}

	/**
	 * Method 'setMatchername4'
	 * 
	 * @param matchername4
	 */
	public void setMatchername4(String matchername4)
	{
		this.matchername4 = matchername4;
	}

	/**
	 * Method 'getMatchervalue4'
	 * 
	 * @return String
	 */
	public String getMatchervalue4()
	{
		return matchervalue4;
	}

	/**
	 * Method 'setMatchervalue4'
	 * 
	 * @param matchervalue4
	 */
	public void setMatchervalue4(String matchervalue4)
	{
		this.matchervalue4 = matchervalue4;
	}

	/**
	 * Method 'getWeightvalue4'
	 * 
	 * @return double
	 */
	public double getWeightvalue4()
	{
		return weightvalue4;
	}

	/**
	 * Method 'setWeightvalue4'
	 * 
	 * @param weightvalue4
	 */
	public void setWeightvalue4(double weightvalue4)
	{
		this.weightvalue4 = weightvalue4;
		this.weightvalue4Null = false;
	}

	/**
	 * Method 'setWeightvalue4Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue4Null(boolean value)
	{
		this.weightvalue4Null = value;
	}

	/**
	 * Method 'isWeightvalue4Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue4Null()
	{
		return weightvalue4Null;
	}

	/**
	 * Method 'getMatchername5'
	 * 
	 * @return String
	 */
	public String getMatchername5()
	{
		return matchername5;
	}

	/**
	 * Method 'setMatchername5'
	 * 
	 * @param matchername5
	 */
	public void setMatchername5(String matchername5)
	{
		this.matchername5 = matchername5;
	}

	/**
	 * Method 'getMatchervalue5'
	 * 
	 * @return String
	 */
	public String getMatchervalue5()
	{
		return matchervalue5;
	}

	/**
	 * Method 'setMatchervalue5'
	 * 
	 * @param matchervalue5
	 */
	public void setMatchervalue5(String matchervalue5)
	{
		this.matchervalue5 = matchervalue5;
	}

	/**
	 * Method 'getWeightvalue5'
	 * 
	 * @return double
	 */
	public double getWeightvalue5()
	{
		return weightvalue5;
	}

	/**
	 * Method 'setWeightvalue5'
	 * 
	 * @param weightvalue5
	 */
	public void setWeightvalue5(double weightvalue5)
	{
		this.weightvalue5 = weightvalue5;
		this.weightvalue5Null = false;
	}

	/**
	 * Method 'setWeightvalue5Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue5Null(boolean value)
	{
		this.weightvalue5Null = value;
	}

	/**
	 * Method 'isWeightvalue5Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue5Null()
	{
		return weightvalue5Null;
	}

	/**
	 * Method 'getMatchername6'
	 * 
	 * @return String
	 */
	public String getMatchername6()
	{
		return matchername6;
	}

	/**
	 * Method 'setMatchername6'
	 * 
	 * @param matchername6
	 */
	public void setMatchername6(String matchername6)
	{
		this.matchername6 = matchername6;
	}

	/**
	 * Method 'getMatchervalue6'
	 * 
	 * @return String
	 */
	public String getMatchervalue6()
	{
		return matchervalue6;
	}

	/**
	 * Method 'setMatchervalue6'
	 * 
	 * @param matchervalue6
	 */
	public void setMatchervalue6(String matchervalue6)
	{
		this.matchervalue6 = matchervalue6;
	}

	/**
	 * Method 'getWeightvalue6'
	 * 
	 * @return double
	 */
	public double getWeightvalue6()
	{
		return weightvalue6;
	}

	/**
	 * Method 'setWeightvalue6'
	 * 
	 * @param weightvalue6
	 */
	public void setWeightvalue6(double weightvalue6)
	{
		this.weightvalue6 = weightvalue6;
		this.weightvalue6Null = false;
	}

	/**
	 * Method 'setWeightvalue6Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue6Null(boolean value)
	{
		this.weightvalue6Null = value;
	}

	/**
	 * Method 'isWeightvalue6Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue6Null()
	{
		return weightvalue6Null;
	}

	/**
	 * Method 'getMatchername7'
	 * 
	 * @return String
	 */
	public String getMatchername7()
	{
		return matchername7;
	}

	/**
	 * Method 'setMatchername7'
	 * 
	 * @param matchername7
	 */
	public void setMatchername7(String matchername7)
	{
		this.matchername7 = matchername7;
	}

	/**
	 * Method 'getMatchervalue7'
	 * 
	 * @return String
	 */
	public String getMatchervalue7()
	{
		return matchervalue7;
	}

	/**
	 * Method 'setMatchervalue7'
	 * 
	 * @param matchervalue7
	 */
	public void setMatchervalue7(String matchervalue7)
	{
		this.matchervalue7 = matchervalue7;
	}

	/**
	 * Method 'getWeightvalue7'
	 * 
	 * @return double
	 */
	public double getWeightvalue7()
	{
		return weightvalue7;
	}

	/**
	 * Method 'setWeightvalue7'
	 * 
	 * @param weightvalue7
	 */
	public void setWeightvalue7(double weightvalue7)
	{
		this.weightvalue7 = weightvalue7;
		this.weightvalue7Null = false;
	}

	/**
	 * Method 'setWeightvalue7Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue7Null(boolean value)
	{
		this.weightvalue7Null = value;
	}

	/**
	 * Method 'isWeightvalue7Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue7Null()
	{
		return weightvalue7Null;
	}

	/**
	 * Method 'getMatchername8'
	 * 
	 * @return String
	 */
	public String getMatchername8()
	{
		return matchername8;
	}

	/**
	 * Method 'setMatchername8'
	 * 
	 * @param matchername8
	 */
	public void setMatchername8(String matchername8)
	{
		this.matchername8 = matchername8;
	}

	/**
	 * Method 'getMatchervalue8'
	 * 
	 * @return String
	 */
	public String getMatchervalue8()
	{
		return matchervalue8;
	}

	/**
	 * Method 'setMatchervalue8'
	 * 
	 * @param matchervalue8
	 */
	public void setMatchervalue8(String matchervalue8)
	{
		this.matchervalue8 = matchervalue8;
	}

	/**
	 * Method 'getWeightvalue8'
	 * 
	 * @return double
	 */
	public double getWeightvalue8()
	{
		return weightvalue8;
	}

	/**
	 * Method 'setWeightvalue8'
	 * 
	 * @param weightvalue8
	 */
	public void setWeightvalue8(double weightvalue8)
	{
		this.weightvalue8 = weightvalue8;
		this.weightvalue8Null = false;
	}

	/**
	 * Method 'setWeightvalue8Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue8Null(boolean value)
	{
		this.weightvalue8Null = value;
	}

	/**
	 * Method 'isWeightvalue8Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue8Null()
	{
		return weightvalue8Null;
	}

	/**
	 * Method 'getMatchername9'
	 * 
	 * @return String
	 */
	public String getMatchername9()
	{
		return matchername9;
	}

	/**
	 * Method 'setMatchername9'
	 * 
	 * @param matchername9
	 */
	public void setMatchername9(String matchername9)
	{
		this.matchername9 = matchername9;
	}

	/**
	 * Method 'getMatchervalue9'
	 * 
	 * @return String
	 */
	public String getMatchervalue9()
	{
		return matchervalue9;
	}

	/**
	 * Method 'setMatchervalue9'
	 * 
	 * @param matchervalue9
	 */
	public void setMatchervalue9(String matchervalue9)
	{
		this.matchervalue9 = matchervalue9;
	}

	/**
	 * Method 'getWeightvalue9'
	 * 
	 * @return double
	 */
	public double getWeightvalue9()
	{
		return weightvalue9;
	}

	/**
	 * Method 'setWeightvalue9'
	 * 
	 * @param weightvalue9
	 */
	public void setWeightvalue9(double weightvalue9)
	{
		this.weightvalue9 = weightvalue9;
		this.weightvalue9Null = false;
	}

	/**
	 * Method 'setWeightvalue9Null'
	 * 
	 * @param value
	 */
	public void setWeightvalue9Null(boolean value)
	{
		this.weightvalue9Null = value;
	}

	/**
	 * Method 'isWeightvalue9Null'
	 * 
	 * @return boolean
	 */
	public boolean isWeightvalue9Null()
	{
		return weightvalue9Null;
	}

	/**
	 * Method 'getThresholdvalue'
	 * 
	 * @return double
	 */
	public double getThresholdvalue()
	{
		return thresholdvalue;
	}

	/**
	 * Method 'setThresholdvalue'
	 * 
	 * @param thresholdvalue
	 */
	public void setThresholdvalue(double thresholdvalue)
	{
		this.thresholdvalue = thresholdvalue;
	}

	/**
	 * Method 'getSessionType'
	 * 
	 * @return String
	 */
	public String getSessionType()
	{
		return sessionType;
	}

	/**
	 * Method 'setSessionType'
	 * 
	 * @param sessionType
	 */
	public void setSessionType(String sessionType)
	{
		this.sessionType = sessionType;
	}

	/**
	 * Method 'getSid'
	 * 
	 * @return String
	 */
	public String getSid()
	{
		return sid;
	}

	/**
	 * Method 'setSid'
	 * 
	 * @param sid
	 */
	public void setSid(String sid)
	{
		this.sid = sid;
	}

	/**
	 * Method 'getStep'
	 * 
	 * @return short
	 */
	public short getStep()
	{
		return step;
	}

	/**
	 * Method 'setStep'
	 * 
	 * @param step
	 */
	public void setStep(short step)
	{
		this.step = step;
	}

	/**
	 * Method 'getIsFinalized'
	 * 
	 * @return int
	 */
	public int getIsFinalized()
	{
		return isFinalized;
	}

	/**
	 * Method 'setIsFinalized'
	 * 
	 * @param isFinalized
	 */
	public void setIsFinalized(int isFinalized)
	{
		this.isFinalized = isFinalized;
	}

	/**
	 * Method 'getUserXml'
	 * 
	 * @return String
	 */
	public String getUserXml()
	{
		return userXml;
	}

	/**
	 * Method 'setUserXml'
	 * 
	 * @param userXml
	 */
	public void setUserXml(String userXml)
	{
		this.userXml = userXml;
	}

	/**
	 * Method 'getUserHistorylistXml'
	 * 
	 * @return String
	 */
	public String getUserHistorylistXml()
	{
		return userHistorylistXml;
	}

	/**
	 * Method 'setUserHistorylistXml'
	 * 
	 * @param userHistorylistXml
	 */
	public void setUserHistorylistXml(String userHistorylistXml)
	{
		this.userHistorylistXml = userHistorylistXml;
	}

	/**
	 * Method 'getUserRelationsHistorylistXml'
	 * 
	 * @return String
	 */
	public String getUserRelationsHistorylistXml()
	{
		return userRelationsHistorylistXml;
	}

	/**
	 * Method 'setUserRelationsHistorylistXml'
	 * 
	 * @param userRelationsHistorylistXml
	 */
	public void setUserRelationsHistorylistXml(String userRelationsHistorylistXml)
	{
		this.userRelationsHistorylistXml = userRelationsHistorylistXml;
	}

	/**
	 * Method 'getUserSuggestionsListXml'
	 * 
	 * @return String
	 */
	public String getUserSuggestionsListXml()
	{
		return userSuggestionsListXml;
	}

	/**
	 * Method 'setUserSuggestionsListXml'
	 * 
	 * @param userSuggestionsListXml
	 */
	public void setUserSuggestionsListXml(String userSuggestionsListXml)
	{
		this.userSuggestionsListXml = userSuggestionsListXml;
	}

	/**
	 * Method 'getUserTempXml'
	 * 
	 * @return String
	 */
	public String getUserTempXml()
	{
		return userTempXml;
	}

	/**
	 * Method 'setUserTempXml'
	 * 
	 * @param userTempXml
	 */
	public void setUserTempXml(String userTempXml)
	{
		this.userTempXml = userTempXml;
	}

	/**
	 * Method 'getCreationTime'
	 * 
	 * @return Date
	 */
	public Date getCreationTime()
	{
		return creationTime;
	}

	/**
	 * Method 'setCreationTime'
	 * 
	 * @param creationTime
	 */
	public void setCreationTime(Date creationTime)
	{
		this.creationTime = creationTime;
	}

	/**
	 * Method 'getLastAccessedTime'
	 * 
	 * @return Date
	 */
	public Date getLastAccessedTime()
	{
		return lastAccessedTime;
	}

	/**
	 * Method 'setLastAccessedTime'
	 * 
	 * @param lastAccessedTime
	 */
	public void setLastAccessedTime(Date lastAccessedTime)
	{
		this.lastAccessedTime = lastAccessedTime;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UserSessions)) {
			return false;
		}
		
		final UserSessions _cast = (UserSessions) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (userid != _cast.userid) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (ontology1 == null ? _cast.ontology1 != ontology1 : !ontology1.equals( _cast.ontology1 )) {
			return false;
		}
		
		if (ontology2 == null ? _cast.ontology2 != ontology2 : !ontology2.equals( _cast.ontology2 )) {
			return false;
		}
		
		if (color1 == null ? _cast.color1 != color1 : !color1.equals( _cast.color1 )) {
			return false;
		}
		
		if (color2 == null ? _cast.color2 != color2 : !color2.equals( _cast.color2 )) {
			return false;
		}
		
		if (matchername0 == null ? _cast.matchername0 != matchername0 : !matchername0.equals( _cast.matchername0 )) {
			return false;
		}
		
		if (matchervalue0 == null ? _cast.matchervalue0 != matchervalue0 : !matchervalue0.equals( _cast.matchervalue0 )) {
			return false;
		}
		
		if (weightvalue0 != _cast.weightvalue0) {
			return false;
		}
		
		if (weightvalue0Null != _cast.weightvalue0Null) {
			return false;
		}
		
		if (matchername1 == null ? _cast.matchername1 != matchername1 : !matchername1.equals( _cast.matchername1 )) {
			return false;
		}
		
		if (matchervalue1 == null ? _cast.matchervalue1 != matchervalue1 : !matchervalue1.equals( _cast.matchervalue1 )) {
			return false;
		}
		
		if (weightvalue1 != _cast.weightvalue1) {
			return false;
		}
		
		if (weightvalue1Null != _cast.weightvalue1Null) {
			return false;
		}
		
		if (matchername2 == null ? _cast.matchername2 != matchername2 : !matchername2.equals( _cast.matchername2 )) {
			return false;
		}
		
		if (matchervalue2 == null ? _cast.matchervalue2 != matchervalue2 : !matchervalue2.equals( _cast.matchervalue2 )) {
			return false;
		}
		
		if (weightvalue2 != _cast.weightvalue2) {
			return false;
		}
		
		if (weightvalue2Null != _cast.weightvalue2Null) {
			return false;
		}
		
		if (matchername3 == null ? _cast.matchername3 != matchername3 : !matchername3.equals( _cast.matchername3 )) {
			return false;
		}
		
		if (matchervalue3 == null ? _cast.matchervalue3 != matchervalue3 : !matchervalue3.equals( _cast.matchervalue3 )) {
			return false;
		}
		
		if (weightvalue3 != _cast.weightvalue3) {
			return false;
		}
		
		if (weightvalue3Null != _cast.weightvalue3Null) {
			return false;
		}
		
		if (matchername4 == null ? _cast.matchername4 != matchername4 : !matchername4.equals( _cast.matchername4 )) {
			return false;
		}
		
		if (matchervalue4 == null ? _cast.matchervalue4 != matchervalue4 : !matchervalue4.equals( _cast.matchervalue4 )) {
			return false;
		}
		
		if (weightvalue4 != _cast.weightvalue4) {
			return false;
		}
		
		if (weightvalue4Null != _cast.weightvalue4Null) {
			return false;
		}
		
		if (matchername5 == null ? _cast.matchername5 != matchername5 : !matchername5.equals( _cast.matchername5 )) {
			return false;
		}
		
		if (matchervalue5 == null ? _cast.matchervalue5 != matchervalue5 : !matchervalue5.equals( _cast.matchervalue5 )) {
			return false;
		}
		
		if (weightvalue5 != _cast.weightvalue5) {
			return false;
		}
		
		if (weightvalue5Null != _cast.weightvalue5Null) {
			return false;
		}
		
		if (matchername6 == null ? _cast.matchername6 != matchername6 : !matchername6.equals( _cast.matchername6 )) {
			return false;
		}
		
		if (matchervalue6 == null ? _cast.matchervalue6 != matchervalue6 : !matchervalue6.equals( _cast.matchervalue6 )) {
			return false;
		}
		
		if (weightvalue6 != _cast.weightvalue6) {
			return false;
		}
		
		if (weightvalue6Null != _cast.weightvalue6Null) {
			return false;
		}
		
		if (matchername7 == null ? _cast.matchername7 != matchername7 : !matchername7.equals( _cast.matchername7 )) {
			return false;
		}
		
		if (matchervalue7 == null ? _cast.matchervalue7 != matchervalue7 : !matchervalue7.equals( _cast.matchervalue7 )) {
			return false;
		}
		
		if (weightvalue7 != _cast.weightvalue7) {
			return false;
		}
		
		if (weightvalue7Null != _cast.weightvalue7Null) {
			return false;
		}
		
		if (matchername8 == null ? _cast.matchername8 != matchername8 : !matchername8.equals( _cast.matchername8 )) {
			return false;
		}
		
		if (matchervalue8 == null ? _cast.matchervalue8 != matchervalue8 : !matchervalue8.equals( _cast.matchervalue8 )) {
			return false;
		}
		
		if (weightvalue8 != _cast.weightvalue8) {
			return false;
		}
		
		if (weightvalue8Null != _cast.weightvalue8Null) {
			return false;
		}
		
		if (matchername9 == null ? _cast.matchername9 != matchername9 : !matchername9.equals( _cast.matchername9 )) {
			return false;
		}
		
		if (matchervalue9 == null ? _cast.matchervalue9 != matchervalue9 : !matchervalue9.equals( _cast.matchervalue9 )) {
			return false;
		}
		
		if (weightvalue9 != _cast.weightvalue9) {
			return false;
		}
		
		if (weightvalue9Null != _cast.weightvalue9Null) {
			return false;
		}
		
		if (thresholdvalue != _cast.thresholdvalue) {
			return false;
		}
		
		if (sessionType == null ? _cast.sessionType != sessionType : !sessionType.equals( _cast.sessionType )) {
			return false;
		}
		
		if (sid == null ? _cast.sid != sid : !sid.equals( _cast.sid )) {
			return false;
		}
		
		if (step != _cast.step) {
			return false;
		}
		
		if (isFinalized != _cast.isFinalized) {
			return false;
		}
		
		if (userXml == null ? _cast.userXml != userXml : !userXml.equals( _cast.userXml )) {
			return false;
		}
		
		if (userHistorylistXml == null ? _cast.userHistorylistXml != userHistorylistXml : !userHistorylistXml.equals( _cast.userHistorylistXml )) {
			return false;
		}
		
		if (userRelationsHistorylistXml == null ? _cast.userRelationsHistorylistXml != userRelationsHistorylistXml : !userRelationsHistorylistXml.equals( _cast.userRelationsHistorylistXml )) {
			return false;
		}
		
		if (userSuggestionsListXml == null ? _cast.userSuggestionsListXml != userSuggestionsListXml : !userSuggestionsListXml.equals( _cast.userSuggestionsListXml )) {
			return false;
		}
		
		if (userTempXml == null ? _cast.userTempXml != userTempXml : !userTempXml.equals( _cast.userTempXml )) {
			return false;
		}
		
		if (creationTime == null ? _cast.creationTime != creationTime : !creationTime.equals( _cast.creationTime )) {
			return false;
		}
		
		if (lastAccessedTime == null ? _cast.lastAccessedTime != lastAccessedTime : !lastAccessedTime.equals( _cast.lastAccessedTime )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + userid;
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		if (ontology1 != null) {
			_hashCode = 29 * _hashCode + ontology1.hashCode();
		}
		
		if (ontology2 != null) {
			_hashCode = 29 * _hashCode + ontology2.hashCode();
		}
		
		if (color1 != null) {
			_hashCode = 29 * _hashCode + color1.hashCode();
		}
		
		if (color2 != null) {
			_hashCode = 29 * _hashCode + color2.hashCode();
		}
		
		if (matchername0 != null) {
			_hashCode = 29 * _hashCode + matchername0.hashCode();
		}
		
		if (matchervalue0 != null) {
			_hashCode = 29 * _hashCode + matchervalue0.hashCode();
		}
		
		long temp_weightvalue0 = Double.doubleToLongBits(weightvalue0);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue0 ^ (temp_weightvalue0 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue0Null ? 1 : 0);
		if (matchername1 != null) {
			_hashCode = 29 * _hashCode + matchername1.hashCode();
		}
		
		if (matchervalue1 != null) {
			_hashCode = 29 * _hashCode + matchervalue1.hashCode();
		}
		
		long temp_weightvalue1 = Double.doubleToLongBits(weightvalue1);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue1 ^ (temp_weightvalue1 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue1Null ? 1 : 0);
		if (matchername2 != null) {
			_hashCode = 29 * _hashCode + matchername2.hashCode();
		}
		
		if (matchervalue2 != null) {
			_hashCode = 29 * _hashCode + matchervalue2.hashCode();
		}
		
		long temp_weightvalue2 = Double.doubleToLongBits(weightvalue2);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue2 ^ (temp_weightvalue2 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue2Null ? 1 : 0);
		if (matchername3 != null) {
			_hashCode = 29 * _hashCode + matchername3.hashCode();
		}
		
		if (matchervalue3 != null) {
			_hashCode = 29 * _hashCode + matchervalue3.hashCode();
		}
		
		long temp_weightvalue3 = Double.doubleToLongBits(weightvalue3);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue3 ^ (temp_weightvalue3 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue3Null ? 1 : 0);
		if (matchername4 != null) {
			_hashCode = 29 * _hashCode + matchername4.hashCode();
		}
		
		if (matchervalue4 != null) {
			_hashCode = 29 * _hashCode + matchervalue4.hashCode();
		}
		
		long temp_weightvalue4 = Double.doubleToLongBits(weightvalue4);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue4 ^ (temp_weightvalue4 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue4Null ? 1 : 0);
		if (matchername5 != null) {
			_hashCode = 29 * _hashCode + matchername5.hashCode();
		}
		
		if (matchervalue5 != null) {
			_hashCode = 29 * _hashCode + matchervalue5.hashCode();
		}
		
		long temp_weightvalue5 = Double.doubleToLongBits(weightvalue5);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue5 ^ (temp_weightvalue5 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue5Null ? 1 : 0);
		if (matchername6 != null) {
			_hashCode = 29 * _hashCode + matchername6.hashCode();
		}
		
		if (matchervalue6 != null) {
			_hashCode = 29 * _hashCode + matchervalue6.hashCode();
		}
		
		long temp_weightvalue6 = Double.doubleToLongBits(weightvalue6);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue6 ^ (temp_weightvalue6 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue6Null ? 1 : 0);
		if (matchername7 != null) {
			_hashCode = 29 * _hashCode + matchername7.hashCode();
		}
		
		if (matchervalue7 != null) {
			_hashCode = 29 * _hashCode + matchervalue7.hashCode();
		}
		
		long temp_weightvalue7 = Double.doubleToLongBits(weightvalue7);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue7 ^ (temp_weightvalue7 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue7Null ? 1 : 0);
		if (matchername8 != null) {
			_hashCode = 29 * _hashCode + matchername8.hashCode();
		}
		
		if (matchervalue8 != null) {
			_hashCode = 29 * _hashCode + matchervalue8.hashCode();
		}
		
		long temp_weightvalue8 = Double.doubleToLongBits(weightvalue8);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue8 ^ (temp_weightvalue8 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue8Null ? 1 : 0);
		if (matchername9 != null) {
			_hashCode = 29 * _hashCode + matchername9.hashCode();
		}
		
		if (matchervalue9 != null) {
			_hashCode = 29 * _hashCode + matchervalue9.hashCode();
		}
		
		long temp_weightvalue9 = Double.doubleToLongBits(weightvalue9);
		_hashCode = 29 * _hashCode + (int) (temp_weightvalue9 ^ (temp_weightvalue9 >>> 32));
		_hashCode = 29 * _hashCode + (weightvalue9Null ? 1 : 0);
		long temp_thresholdvalue = Double.doubleToLongBits(thresholdvalue);
		_hashCode = 29 * _hashCode + (int) (temp_thresholdvalue ^ (temp_thresholdvalue >>> 32));
		if (sessionType != null) {
			_hashCode = 29 * _hashCode + sessionType.hashCode();
		}
		
		if (sid != null) {
			_hashCode = 29 * _hashCode + sid.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) step;
		_hashCode = 29 * _hashCode + isFinalized;
		if (userXml != null) {
			_hashCode = 29 * _hashCode + userXml.hashCode();
		}
		
		if (userHistorylistXml != null) {
			_hashCode = 29 * _hashCode + userHistorylistXml.hashCode();
		}
		
		if (userRelationsHistorylistXml != null) {
			_hashCode = 29 * _hashCode + userRelationsHistorylistXml.hashCode();
		}
		
		if (userSuggestionsListXml != null) {
			_hashCode = 29 * _hashCode + userSuggestionsListXml.hashCode();
		}
		
		if (userTempXml != null) {
			_hashCode = 29 * _hashCode + userTempXml.hashCode();
		}
		
		if (creationTime != null) {
			_hashCode = 29 * _hashCode + creationTime.hashCode();
		}
		
		if (lastAccessedTime != null) {
			_hashCode = 29 * _hashCode + lastAccessedTime.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UserSessionsPk
	 */
	public UserSessionsPk createPk()
	{
		return new UserSessionsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "se.liu.ida.sambo.dto.UserSessions: " );
		ret.append( "id=" + id );
		ret.append( ", userid=" + userid );
		ret.append( ", email=" + email );
		ret.append( ", ontology1=" + ontology1 );
		ret.append( ", ontology2=" + ontology2 );
		ret.append( ", color1=" + color1 );
		ret.append( ", color2=" + color2 );
		ret.append( ", matchername0=" + matchername0 );
		ret.append( ", matchervalue0=" + matchervalue0 );
		ret.append( ", weightvalue0=" + weightvalue0 );
		ret.append( ", matchername1=" + matchername1 );
		ret.append( ", matchervalue1=" + matchervalue1 );
		ret.append( ", weightvalue1=" + weightvalue1 );
		ret.append( ", matchername2=" + matchername2 );
		ret.append( ", matchervalue2=" + matchervalue2 );
		ret.append( ", weightvalue2=" + weightvalue2 );
		ret.append( ", matchername3=" + matchername3 );
		ret.append( ", matchervalue3=" + matchervalue3 );
		ret.append( ", weightvalue3=" + weightvalue3 );
		ret.append( ", matchername4=" + matchername4 );
		ret.append( ", matchervalue4=" + matchervalue4 );
		ret.append( ", weightvalue4=" + weightvalue4 );
		ret.append( ", matchername5=" + matchername5 );
		ret.append( ", matchervalue5=" + matchervalue5 );
		ret.append( ", weightvalue5=" + weightvalue5 );
		ret.append( ", matchername6=" + matchername6 );
		ret.append( ", matchervalue6=" + matchervalue6 );
		ret.append( ", weightvalue6=" + weightvalue6 );
		ret.append( ", matchername7=" + matchername7 );
		ret.append( ", matchervalue7=" + matchervalue7 );
		ret.append( ", weightvalue7=" + weightvalue7 );
		ret.append( ", matchername8=" + matchername8 );
		ret.append( ", matchervalue8=" + matchervalue8 );
		ret.append( ", weightvalue8=" + weightvalue8 );
		ret.append( ", matchername9=" + matchername9 );
		ret.append( ", matchervalue9=" + matchervalue9 );
		ret.append( ", weightvalue9=" + weightvalue9 );
		ret.append( ", thresholdvalue=" + thresholdvalue );
		ret.append( ", sessionType=" + sessionType );
		ret.append( ", sid=" + sid );
		ret.append( ", step=" + step );
		ret.append( ", isFinalized=" + isFinalized );
		ret.append( ", userXml=" + userXml );
		ret.append( ", userHistorylistXml=" + userHistorylistXml );
		ret.append( ", userRelationsHistorylistXml=" + userRelationsHistorylistXml );
		ret.append( ", userSuggestionsListXml=" + userSuggestionsListXml );
		ret.append( ", userTempXml=" + userTempXml );
		ret.append( ", creationTime=" + creationTime );
		ret.append( ", lastAccessedTime=" + lastAccessedTime );
		return ret.toString();
	}

}
