
<p  class= 'blue'>Due to the explosion of the amount of biomedical data, knowledge and tools 
that are often publicly available over the Web,
 a number of difficulties are experienced by biomedical researchers. 
For instance, it is difficult to find, retrieve and integrate information 
that is relevatn to their research task. Ontologies and the vision of a Semantic Web for life sciences alleviate these difficulties.
Nowdays many biomedical ontologies have been developed and many of these ontologies contain overlapping infromation. 
To be able to use multiple ontologies they have to be aligned or merged. </p>


<p class= 'blue'>SAMBO is a <b><font color="#000000"> S</font></b>ystem for <b><font color="#000000">A</font></b>ligning 
and <b><font color="#000000">M</font></b>erging <b><font color="#000000">B</font></b>iomedical <b><font color="#000000">O</font></b>ntologies.
 In SAMBO the alignment process is separated into steps, aligning relations and aligning concepts. 
The user can perform the alignment manually or based on the suggestions.
The suggestions are proposed by different alignment strategies as well as their combinations. 
After the user accomplishes the alignment process, the system can be asked to compute a merged ontology from 
the source ontologies and their identified alignments. 
Furthermore, SAMBO also provides a number of reasoning services, such as checking whether the new ontology is consistent,
whether there are cycles in the new ontology and whether there are unsatisfiable concepts.</p>
