<ul class= 'blue'>

<li> Lambrix P, Tan H, <a class='menulink' href="http://dx.doi.org/10.1016/j.websem.2006.05.003">
       'SAMBO - A System for Aligning and Merging Biomedical Ontologies'</a>,
       <em>Journal of Web Semantics, Special issue on Semantic Web for the Life Sciences</em>, 4(3):196-206, 2006. 
<br>&nbsp;
<li> Chen B, Tan H, Lambrix P,
       `Structure-based filtering for ontology alignment',
       <em>Proceedings of the IEEE WETICE Workshop on Semantic Technologies in Collaborative Applications</em>, pp 364-369, 2006.
<br>&nbsp;
<li> Tan H, Jakoniene V, Lambrix P, Aberg J, Shahmehri N, 
       <a class='menulink' href="http://dx.doi.org/10.1007/11683568_1">
       `Alignment of Biomedical Ontologies using Life Science Literature'</a>,
       <em>Proceedings of the International Workshop on Knowledge Discovery in Life Science Literature</em>, LNBI 3886, pp 1-17, Singapore, 2006. &copy; Springer-Verlag. 
<br>&nbsp;
<li> Lambrix P, Tan H, 
     <a class='menulink' href="http://www.ida.liu.se/labs/iislab/people/patla/publications/ppswr05-abstract.pdf"> `A Framework for Aligning Ontologies'<a>,
     <em> Proceedings of the Third Workshop on Principles and Practice of Semantic Web Reasoning</em>, LNCS,
     Dagstuhl, Germany, 2005. &copy; Springer-Verlag.
<br>&nbsp; 

<!--
<li> Lambrix P, Tan H, 
     `Merging DAML+OIL Ontologies', in Barzdins, J. and Caplinskas, A. (eds) 
     <em>Databases and Information Systems (Selected Papers from the Sixth International Baltic Conference DB&IS'2004)</em>, pp 249-258, IOS Press, 2005. ISBN: 1 58603 485 5. 
<br>&nbsp;
<li> Lambrix, P., Edberg, A., Manis, C., Tan, H.,
       <a class='menulink' href="http://sunsite.informatik.rwth-aachen.de/Publications/CEUR-WS/Vol-81/lambrix.ps">`Merging DAML+OIL bio-ontologies'</a>,
      <em>Proceedings of the International Workshop on Description Logics</em>,
      Rome, Italy, 2003. </li>

</ul>

-->